GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzb3V0bG9vay5jb20iLCJpYXQiOjE2Nzk2Mjc5OTgsImV4cCI6MTY3OTYyOTc5OH0.l8tirPtEn_jHmNpOJf1YHY5cEaHJpmDod2tx8tVI0_U

### admin: 63fe3da0bfd22ab2dd64e32a
### 63fe157191a7238e2269f43c
###63fe36d2bfd22ab2dd64e323
POST http://localhost:4000/users
Content-Type:application/json

{
    "email": "wade3.hama@outlook.com",
    "password": "3333",
    "firstName": "wadeh",
    "lastName": "hama",
    "age": 22,
    "userType": "admin"
}

### 641d11c48fe77e7af17d0823
GET http://localhost:4000/users/641d11c48fe77e7af17d0823
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzb3V0bG9vay5jb20iLCJpYXQiOjE2Nzk2Mjk1MTIsImV4cCI6MTY3OTYzMTMxMn0.lxTExp2L92CQmzhVkvU5o-8vgFJs1yzree8hrEOG5V0

### "acessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzb3V0bG9vay5jb20iLCJpYXQiOjE2Nzc2MDYzNDUsImV4cCI6MTY3NzYwNjM3NX0._ikk9Z0mDnm1x4UBXRdFNjh9MR17bwe5YI2n8BK1uSk",
### "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzb3V0bG9vay5jb20iLCJpYXQiOjE2Nzc2MDYzNDV9.iOhiX85T-QrdaUHLL1jaqjR1JczypD8iQcdqzesbLAk"
### admin: 63fe3da0bfd22ab2dd64e32a 
POST http://localhost:4000/login
Content-Type:application/json

{
    "email": "wade3.hama@outlook.com",
    "password":"3333"
}

###
PATCH http://localhost:4000/users/641dba3d41756e238ccd1cfb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzLmhhbWFAb3V0bG9vay5jb20iLCJpYXQiOjE2Nzk3OTAwMjksImV4cCI6MTY3OTc5MTgyOX0.To0lcYad7jor605RXZfdwJaUSihG9Xf5eR9rep0fiOk
Content-Type:application/json

{
    "firstName": "walidddd",
    "lastName": "alshhhh",
    "age": 23,
    "userType": "student",
    "subscribedTo" : ["Company f"],
    "savedPostings" : ["post 2"]
}

###

DELETE http://localhost:4000/users/63fe153991a7238e2269f438
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzb3V0bG9vay5jb20iLCJpYXQiOjE2Nzk2Mjc5OTgsImV4cCI6MTY3OTYyOTc5OH0.l8tirPtEn_jHmNpOJf1YHY5cEaHJpmDod2tx8tVI0_U

###

POST http://localhost:4000/subscribe
Content-Type:application/json

{
    "email": "wade3_hamati@outlook.com"
}

###

PATCH http://localhost:4000/subscribe/641dba3d41756e238ccd1cfb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzLmhhbWFAb3V0bG9vay5jb20iLCJpYXQiOjE2Nzk3OTAwMjksImV4cCI6MTY3OTc5MTgyOX0.To0lcYad7jor605RXZfdwJaUSihG9Xf5eR9rep0fiOk
Content-Type:application/json

{
    "subscribedTo" : ["Company g"]
}

### 641d11c48fe77e7af17d0823
GET http://localhost:4000/users/641dba3d41756e238ccd1cfb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhZGUzLmhhbWFAb3V0bG9vay5jb20iLCJpYXQiOjE2Nzk3OTAwMjksImV4cCI6MTY3OTc5MTgyOX0.To0lcYad7jor605RXZfdwJaUSihG9Xf5eR9rep0fiOk
