name: Node.js CI with SonarCloud

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - 'main'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install and test frontend
        working-directory: ./client
        env:
          CI: ""
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          npm ci
          npm run build --if-present
          npm test
  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci
# @TODO fix tests and uncomment the code
      # - name: Test
      #   working-directory: ./server
      #   env:
      #     MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      #     MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      #     MONGO_HOST: ${{ secrets.MONGO_HOST }}
      #     MONGO_DB: ${{ secrets.MONGO_DB }}
      #     PORT: ${{ secrets.PORT }}
      #     JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
      #     JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
      #   run: npm test

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
